server:
  port: 8080

  servlet:
    encoding:
      charset: UTF-8
      enabled: on
      force: on

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/h2/base
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

  jackson:
    serialization:
      INDENT_OUTPUT: true # print pretty json

logging:
  level:
    org:
      hibernate:
        type: TRACE
      springframework:
        security: DEBUG
        web: DEBUG
        web.filter: DEBUG
        orm:
          jpa: DEBUG